# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qbec < Formula
  desc "Qbec (pronounced like the Canadian province) is a CLI tool that allows you to create Kubernetes objects on multiple Kubernetes clusters or namespaces configured correctly for the target environment in question."
  homepage "https://qbec.io/"
  version "0.21.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/splunk/qbec/releases/download/v0.21.0/qbec-darwin-amd64.tar.gz"
      sha256 "6ad8b04ec1f862130ba7d75875349ffa7cfb2d27722b02c43d95609ef80a1a0e"

      def install
        bin.install "qbec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/splunk/qbec/releases/download/v0.21.0/qbec-darwin-arm64.tar.gz"
      sha256 "d4662368b37ca299882b060d9259a6c9ce1b04f1ce60c89d93e3647252f714c4"

      def install
        bin.install "qbec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/splunk/qbec/releases/download/v0.21.0/qbec-linux-amd64.tar.gz"
      sha256 "313e4d3dcd55bae4999b11614da6b553c6c370e29ddfe866b0b33c4ba3b0b0b7"
      def install
        bin.install "qbec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/splunk/qbec/releases/download/v0.21.0/qbec-linux-arm64.tar.gz"
      sha256 "8a79f61203fd1cb5a8d39260c53660c0c0b1ec6566c211183396071df7785823"
      def install
        bin.install "qbec"
      end
    end
  end

  test do
    system "#{bin}/qbec version"
  end
end
